name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: node:14.15
    steps:  
      -
        name: Build electron app for Windows, Mac OS, Linux
        run: |
          yarn install --development
          mkdir -p build
          yarn build
          yarn dist
